import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import Home from "@/Components/Home"
import Contact from "@/Components/Contact"
import Gallery from "@/Components/Gallery"
import Services from "@/Components/Services";
import Detail from "@/Components/Detail";
import Feature from "@/Components/Feature";
import SecondFeature from "@/Components/SecondFeature";
import Preview from "@/Components/Preview";
import Form from "@/Components/Form";
import Footer from '@/Components/Footer'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <Header/>
        <Home/>
        <Contact/>
        <Gallery/>
        <Services/>
        <Detail/>
        <Feature/>
        <SecondFeature/>
        <Preview/>
        <Form/>
        <Footer/>
        {children}
        
      </body>
    </html>
  );
}
