import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import Hero from "@/Components/Hero"
import Contact from "@/Components/Contact"
import Gallery from "@/Components/Gallery"
import Services from "@/Components/Services";
import Detail from "@/Components/Detail";
import Reviews from "@/Components/Reviews";
import Feature from "@/Components/Feature";
import Preview from "@/Components/Preview";
import Form from "@/Components/Form";
import Footer from '@/Components/Footer'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Arham HABITAT",
  description: "Generated by Arham HABITAT",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
        <Header/>
        <Hero/>
        <Contact/>
        <Gallery/>
        <Services/>
        <Detail/>
        <Reviews/>
        <Feature/>
        <Preview/>
        <Form/>
        <Footer/>
        {children}
        
      </body>
    </html>
  );
}
